/**
 * /disclaimer — Disclaimer.
 *
 * Testnet-only, self-custodial, experimental crypto software. The three
 * things this MUST land (§5 claims-sweep, §6 no-false-green):
 *   1. Testnet tokens have NO monetary value — nobody is buying anything real.
 *   2. Self-custody = the user is responsible for their keys AND their pool
 *      claim secrets. Lose the claim URL → funds are unrecoverable. This is
 *      the single most important warning given the /fund + /pay flows.
 *   3. Unaudited, "as is", no warranty, limitation of liability.
 *
 * Keep claims true: no "audited", no "guaranteed anonymous". The pool gives
 * cohort-based privacy, not cryptographic anonymity — matches the on-site
 * PoolView disclaimer and the README.
 *
 * SEO: per-page <title> + meta description via a tiny effect (no dep).
 */

import { useSeo } from "@/hooks/useSeo";
import { Link } from "react-router-dom";
import { ChevronLeft } from "lucide-react";

const H = ({ children }: { children: React.ReactNode }) => (
  <h2 className="text-foreground text-base font-medium mt-8 mb-2">{children}</h2>
);

const Disclaimer = () => {
  useSeo({
    title: "Disclaimer — cyrusthegreat.dev",
    description: "Disclaimer for cyrusthegreat.dev — an experimental, unaudited, self-custodial testnet dapp. Testnet tokens have no value. Not financial advice. No warranty.",
    path: "/disclaimer",
  });

  return (
    <div className="max-w-3xl mx-auto px-4 py-10 text-muted-foreground text-sm leading-relaxed">
      <Link to="/" className="inline-flex items-center text-xs text-muted-foreground hover:text-foreground mb-6">
        <ChevronLeft className="w-4 h-4 mr-1" /> Back to cyrusthegreat.dev
      </Link>

      <h1 className="text-2xl text-foreground font-bold mb-1">Disclaimer</h1>
      <p className="text-xs text-muted-foreground/70 mb-6">Last updated: July 2026</p>

      <div className="rounded-md border border-yellow-500/30 bg-yellow-500/5 px-3 py-2 mb-6">
        <p className="text-xs text-yellow-200/90">
          <strong>Testnet only.</strong> cyrusthegreat.dev runs on public test networks. Testnet tokens have
          <span className="text-yellow-100"> no monetary value</span> and cannot be exchanged for money. Nothing here is a
          real financial product.
        </p>
      </div>

      <H>Informational &amp; experimental — not advice</H>
      <p>
        cyrusthegreat.dev is an independent, experimental project provided for demonstration and testing.
        Nothing on this site is legal, financial, tax, investment, or other professional advice. Do not make
        any decision based on this site. Cryptocurrency and smart-contract interactions carry risk, including
        total loss.
      </p>

      <H>Self-custody — you are in control, and responsible</H>
      <p>
        This is <span className="text-foreground">self-custodial</span> software. You hold your own wallet keys, and the app
        never takes custody of your funds. That also means <span className="text-foreground">you</span> are solely responsible for:
      </p>
      <ul className="list-disc pl-5 space-y-1 mt-2">
        <li>Keeping your wallet's seed phrase and private keys safe.</li>
        <li>
          Keeping any <span className="text-foreground">claim link / QR / secret</span> generated by the anonymity pool
          (CyrusTeleport). If you lose it and it is not in your browser's notebook, the funds it unlocks are
          <span className="text-foreground"> permanently unrecoverable</span> — no one, including us, can restore them.
        </li>
        <li>Verifying every recipient address and amount before you confirm a transaction. On-chain transactions are irreversible.</li>
      </ul>

      <H>Privacy is cohort-based, not absolute</H>
      <p>
        The optional privacy pool provides <span className="text-foreground">cohort-based</span> privacy (your action is grouped
        with others in the same time window and amount bucket). It is <span className="text-foreground">not</span> cryptographic
        anonymity, and it is not a mixer marketed for evading lawful obligations. Do not rely on it for
        anything where deanonymisation would cause you harm.
      </p>

      <H>Unaudited software</H>
      <p>
        The smart contracts and interface are <span className="text-foreground">experimental and have not been formally audited.</span> They
        may contain bugs. A formal audit is planned before any mainnet launch. Until then, treat everything
        here as test software.
      </p>

      <H>No warranty · limitation of liability</H>
      <p>
        This website, its contracts, and its content are provided "as is" and "as available", without
        warranties of any kind, express or implied. To the fullest extent permitted by applicable law, the
        operators are not liable for any direct, indirect, incidental, or consequential damages arising from
        your use of, or reliance on, this site, its contracts, or any token.
      </p>

      <H>Compliance is your responsibility</H>
      <p>
        You are responsible for complying with the laws and regulations that apply to you, including tax and
        financial-regulatory obligations in your jurisdiction. Do not use this site where doing so would be
        unlawful.
      </p>

      <p className="text-xs text-muted-foreground/50 mt-10">
        This document is provided for transparency and is not legal advice.
      </p>
    </div>
  );
};

export default Disclaimer;
