/**
 * /fund — donor-facing campaign page.
 *
 * Lands here from a URL generated by /fundraise. URL params:
 *   ?to=0xWallet      — campaign owner's wallet (required)
 *   &title=…          — campaign title (required, displayed prominently)
 *   &desc=…           — optional description
 *   &goal=…           — optional display target
 *   &token=USD1       — donation token symbol
 *
 * Renders: campaign hero (title + description + goal) → donate CTA that
 * routes to /pay with the campaign's recipient pre-locked.
 *
 * Why this is a thin wrapper around /pay: the campaign page sells the
 * cause; /pay does the actual donation flow. Splitting them means the
 * privacy-pool primitive lives in one place (PayForm) instead of being
 * duplicated. Same security, same simplified UI when arriving via a
 * pre-filled link, same Apple-Pay-coming-soon scaffold.
 *
 * Future enhancement (not in v1): on-chain progress bar via event
 * indexing. Would require server-side indexer OR a known-recipient
 * filter on commit events, both non-trivial. For now the goal field is
 * display-only.
 */

import { useState, useMemo } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useChainId } from "wagmi";
import { formatUnits, type Address } from "viem";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ChevronLeft, HeartHandshake, ExternalLink, AlertTriangle, TrendingUp, Loader2 } from "lucide-react";
import { WEB3_CONFIG } from "@/config/web3";
import {
  POOL_TOKENS_BY_CHAIN,
  usePoolRevealsForRecipient,
} from "@/hooks/usePool";

const Fund = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [parseError] = useState<string | null>(null);

  const recipient = searchParams.get("to") ?? "";
  const title = searchParams.get("title") ?? "";
  const description = searchParams.get("desc") ?? "";
  const goal = searchParams.get("goal") ?? "";
  const tokenSymbol = searchParams.get("token") ?? "USD1";

  const recipientValid = /^0x[a-fA-F0-9]{40}$/.test(recipient);
  const titleValid = title.trim().length > 0;

  // Resolve the campaign's token address from the symbol via the
  // current chain's registry. If wallet isn't on a supported chain,
  // fallback to Sepolia (most-deployed). If token symbol isn't found,
  // we'll skip progress + show a one-line caveat.
  const walletChainId = useChainId();
  const chainForTokens = walletChainId ?? 11155111;
  const availableTokens = POOL_TOKENS_BY_CHAIN[chainForTokens] ?? POOL_TOKENS_BY_CHAIN[11155111] ?? [];
  const matchedToken = useMemo(
    () => availableTokens.find(t => t.symbol.toLowerCase() === tokenSymbol.toLowerCase()),
    [availableTokens, tokenSymbol],
  );
  const tokenAddress = matchedToken?.address as Address | undefined;
  const tokenDecimals = matchedToken?.decimals ?? 18;

  // Live progress — sums PoolReveal events to this recipient for this
  // token on the current chain. Updates every 30s. Returns zeros while
  // loading or if the chain RPC's getLogs is rate-limited / restricted.
  const { totalRaised, count, isLoading: progressLoading } = usePoolRevealsForRecipient(
    recipientValid ? (recipient as Address) : undefined,
    tokenAddress,
  );

  const goalWei = useMemo(() => {
    if (!goal || !/^\d+(\.\d+)?$/.test(goal)) return undefined;
    try {
      const [whole, frac = ''] = goal.split('.');
      const padded = (whole + frac.padEnd(tokenDecimals, '0')).slice(0, whole.length + tokenDecimals);
      return BigInt(padded);
    } catch { return undefined; }
  }, [goal, tokenDecimals]);

  const progressPercent = goalWei && goalWei > 0n
    ? Math.min(100, Number((totalRaised * 100n) / goalWei))
    : null;

  if (!WEB3_CONFIG.ENABLE_POOL) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12">
        <Card className="p-6 bg-gradient-card backdrop-blur border-vault-primary/30">
          <h1 className="text-xl font-bold mb-2">Fundraising unavailable</h1>
          <p className="text-sm text-muted-foreground">
            The privacy-payment feature isn't enabled on this build.
          </p>
        </Card>
      </div>
    );
  }

  if (!recipientValid || !titleValid || parseError) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12 space-y-4">
        <Button variant="ghost" size="sm" onClick={() => navigate("/")}>
          <ChevronLeft className="w-4 h-4 mr-1" /> Back to vault
        </Button>
        <Card className="p-6 bg-gradient-card backdrop-blur border-red-500/30">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5" />
            <div>
              <h1 className="text-lg font-semibold mb-2">Invalid campaign URL</h1>
              <p className="text-sm text-muted-foreground">
                {parseError ?? (
                  !recipientValid
                    ? "Missing or invalid recipient wallet address (?to= parameter)."
                    : "Missing campaign title (?title= parameter)."
                )}
              </p>
              <p className="text-xs text-muted-foreground mt-2">
                Want to create a campaign? <a href="/fundraise" className="text-vault-primary hover:underline">Start here →</a>
              </p>
            </div>
          </div>
        </Card>
      </div>
    );
  }

  // Build the /pay URL the donate button routes to. Reuse the campaign's
  // token + recipient; donor picks amount on the pay form.
  const payURL = (() => {
    const p = new URLSearchParams();
    p.set("to", recipient);
    p.set("token", tokenSymbol);
    p.set("memo", `Donation · ${title.slice(0, 50)}`);
    return `/pay?${p.toString()}`;
  })();

  return (
    <div className="w-full max-w-2xl mx-auto px-4 py-6 space-y-4">
      <Button variant="ghost" size="sm" onClick={() => navigate("/")} className="text-muted-foreground hover:text-foreground">
        <ChevronLeft className="w-4 h-4 mr-1" /> Back to vault
      </Button>

      {/* Campaign hero */}
      <Card className="p-6 bg-gradient-card backdrop-blur border-vault-primary/30">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-full bg-vault-primary/15">
            <HeartHandshake className="w-5 h-5 text-vault-primary" />
          </div>
          <p className="text-xs text-muted-foreground uppercase tracking-wide">Fundraising campaign</p>
        </div>
        <h1 className="text-2xl font-bold mb-3">{title}</h1>
        {description && (
          <p className="text-sm text-muted-foreground leading-relaxed mb-4">{description}</p>
        )}
        {/* Live progress — sums PoolReveal events on-chain. Shows
            even if no goal is set (just "X raised so far"); with goal,
            adds the progress bar + percentage. */}
        {matchedToken && (
          <div className="bg-vault-primary/5 border border-vault-primary/20 rounded-md px-3 py-3 mb-4 space-y-2">
            <div className="flex items-baseline justify-between gap-2">
              <div className="flex items-center gap-1.5">
                <TrendingUp className="w-3.5 h-3.5 text-vault-primary" />
                <p className="text-xs text-muted-foreground uppercase tracking-wide">Raised so far</p>
                {progressLoading && <Loader2 className="w-3 h-3 animate-spin text-muted-foreground/50" />}
              </div>
              <p className="text-[10px] text-muted-foreground/60">{count} {count === 1 ? 'donation' : 'donations'}</p>
            </div>
            <p className="text-2xl font-mono text-vault-primary">
              {formatUnits(totalRaised, tokenDecimals)} {tokenSymbol}
              {goal && (
                <span className="text-sm text-muted-foreground ml-2">/ {goal} {tokenSymbol}</span>
              )}
            </p>
            {progressPercent !== null && (
              <>
                <div className="h-2 w-full bg-vault-primary/10 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-vault-primary transition-all duration-500"
                    style={{ width: `${progressPercent}%` }}
                  />
                </div>
                <p className="text-[10px] text-muted-foreground/70 text-right">{progressPercent}% of goal</p>
              </>
            )}
            <p className="text-[9px] text-muted-foreground/50 leading-relaxed pt-1">
              Live from on-chain events on the current chain ({chainForTokens === 11155111 ? 'Sepolia' : `chainId ${chainForTokens}`}).
              Last ~7 days of donations. Updates every 30s.
            </p>
          </div>
        )}
        <div className="text-xs text-muted-foreground space-y-1">
          <p><span className="text-foreground">Funds go to:</span> <code className="font-mono text-[10px]">{recipient.slice(0, 8)}…{recipient.slice(-6)}</code></p>
          <p><span className="text-foreground">Token:</span> {tokenSymbol}</p>
          <p><span className="text-foreground">Privacy:</span> donations route through CyrusTeleport's anonymity pool. ~1 hour settlement.</p>
        </div>
      </Card>

      {/* Donate CTA */}
      <Card className="p-6 bg-gradient-card backdrop-blur border-vault-primary/30 text-center space-y-3">
        <p className="text-sm text-muted-foreground">
          Donations are anonymous on-chain — the campaign owner sees the donation amount + your memo (if you add one), not your wallet.
        </p>
        <Button
          onClick={() => navigate(payURL)}
          className="w-full bg-vault-primary text-background hover:bg-vault-primary/90 text-base py-6"
        >
          <HeartHandshake className="w-5 h-5 mr-2" />
          Donate to this campaign
        </Button>
        <a
          href={payURL}
          className="text-xs text-vault-primary hover:underline inline-flex items-center gap-1"
        >
          Open in new tab <ExternalLink className="w-3 h-3" />
        </a>
      </Card>

      {/* Share */}
      <Card className="p-4 bg-vault-primary/5 border-vault-primary/15">
        <p className="text-xs text-muted-foreground">
          💡 Share this campaign URL with anyone — donations come straight to the wallet above, no
          platform cut, no signup required from donors beyond connecting a wallet.
        </p>
      </Card>
    </div>
  );
};

export default Fund;
