/**
 * /fund — donor-facing campaign page.
 *
 * Lands here from a URL generated by /fundraise. URL params:
 *   ?to=0xWallet      — campaign owner's wallet (required)
 *   &title=…          — campaign title (required, displayed prominently)
 *   &desc=…           — optional description
 *   &goal=…           — optional display target
 *   &token=USD1       — donation token symbol
 *
 * Renders: campaign hero (title + description + goal) → donate CTA that
 * routes to /pay with the campaign's recipient pre-locked.
 *
 * Why this is a thin wrapper around /pay: the campaign page sells the
 * cause; /pay does the actual donation flow. Splitting them means the
 * privacy-pool primitive lives in one place (PayForm) instead of being
 * duplicated. Same security, same simplified UI when arriving via a
 * pre-filled link, same Apple-Pay-coming-soon scaffold.
 *
 * Future enhancement (not in v1): on-chain progress bar via event
 * indexing. Would require server-side indexer OR a known-recipient
 * filter on commit events, both non-trivial. For now the goal field is
 * display-only.
 */

import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ChevronLeft, HeartHandshake, ExternalLink, AlertTriangle } from "lucide-react";
import { WEB3_CONFIG } from "@/config/web3";

const Fund = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const [parseError] = useState<string | null>(null);

  const recipient = searchParams.get("to") ?? "";
  const title = searchParams.get("title") ?? "";
  const description = searchParams.get("desc") ?? "";
  const goal = searchParams.get("goal") ?? "";
  const tokenSymbol = searchParams.get("token") ?? "USD1";

  const recipientValid = /^0x[a-fA-F0-9]{40}$/.test(recipient);
  const titleValid = title.trim().length > 0;

  if (!WEB3_CONFIG.ENABLE_POOL) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12">
        <Card className="p-6 bg-gradient-card backdrop-blur border-vault-primary/30">
          <h1 className="text-xl font-bold mb-2">Fundraising unavailable</h1>
          <p className="text-sm text-muted-foreground">
            The privacy-payment feature isn't enabled on this build.
          </p>
        </Card>
      </div>
    );
  }

  if (!recipientValid || !titleValid || parseError) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12 space-y-4">
        <Button variant="ghost" size="sm" onClick={() => navigate("/")}>
          <ChevronLeft className="w-4 h-4 mr-1" /> Back to vault
        </Button>
        <Card className="p-6 bg-gradient-card backdrop-blur border-red-500/30">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-red-400 mt-0.5" />
            <div>
              <h1 className="text-lg font-semibold mb-2">Invalid campaign URL</h1>
              <p className="text-sm text-muted-foreground">
                {parseError ?? (
                  !recipientValid
                    ? "Missing or invalid recipient wallet address (?to= parameter)."
                    : "Missing campaign title (?title= parameter)."
                )}
              </p>
              <p className="text-xs text-muted-foreground mt-2">
                Want to create a campaign? <a href="/fundraise" className="text-vault-primary hover:underline">Start here →</a>
              </p>
            </div>
          </div>
        </Card>
      </div>
    );
  }

  // Build the /pay URL the donate button routes to. Reuse the campaign's
  // token + recipient; donor picks amount on the pay form.
  const payURL = (() => {
    const p = new URLSearchParams();
    p.set("to", recipient);
    p.set("token", tokenSymbol);
    p.set("memo", `Donation · ${title.slice(0, 50)}`);
    return `/pay?${p.toString()}`;
  })();

  return (
    <div className="w-full max-w-2xl mx-auto px-4 py-6 space-y-4">
      <Button variant="ghost" size="sm" onClick={() => navigate("/")} className="text-muted-foreground hover:text-foreground">
        <ChevronLeft className="w-4 h-4 mr-1" /> Back to vault
      </Button>

      {/* Campaign hero */}
      <Card className="p-6 bg-gradient-card backdrop-blur border-vault-primary/30">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-full bg-vault-primary/15">
            <HeartHandshake className="w-5 h-5 text-vault-primary" />
          </div>
          <p className="text-xs text-muted-foreground uppercase tracking-wide">Fundraising campaign</p>
        </div>
        <h1 className="text-2xl font-bold mb-3">{title}</h1>
        {description && (
          <p className="text-sm text-muted-foreground leading-relaxed mb-4">{description}</p>
        )}
        {goal && (
          <div className="bg-vault-primary/5 border border-vault-primary/20 rounded-md px-3 py-2 mb-4">
            <p className="text-xs text-muted-foreground">Goal</p>
            <p className="text-lg font-mono text-vault-primary">{goal} {tokenSymbol}</p>
            <p className="text-[10px] text-muted-foreground/60 mt-1">
              Display target. On-chain progress tracking coming with v3 indexer.
            </p>
          </div>
        )}
        <div className="text-xs text-muted-foreground space-y-1">
          <p><span className="text-foreground">Funds go to:</span> <code className="font-mono text-[10px]">{recipient.slice(0, 8)}…{recipient.slice(-6)}</code></p>
          <p><span className="text-foreground">Token:</span> {tokenSymbol}</p>
          <p><span className="text-foreground">Privacy:</span> donations route through CyrusTeleport's anonymity pool. ~1 hour settlement.</p>
        </div>
      </Card>

      {/* Donate CTA */}
      <Card className="p-6 bg-gradient-card backdrop-blur border-vault-primary/30 text-center space-y-3">
        <p className="text-sm text-muted-foreground">
          Donations are anonymous on-chain — the campaign owner sees the donation amount + your memo (if you add one), not your wallet.
        </p>
        <Button
          onClick={() => navigate(payURL)}
          className="w-full bg-vault-primary text-background hover:bg-vault-primary/90 text-base py-6"
        >
          <HeartHandshake className="w-5 h-5 mr-2" />
          Donate to this campaign
        </Button>
        <a
          href={payURL}
          className="text-xs text-vault-primary hover:underline inline-flex items-center gap-1"
        >
          Open in new tab <ExternalLink className="w-3 h-3" />
        </a>
      </Card>

      {/* Share */}
      <Card className="p-4 bg-vault-primary/5 border-vault-primary/15">
        <p className="text-xs text-muted-foreground">
          💡 Share this campaign URL with anyone — donations come straight to the wallet above, no
          platform cut, no signup required from donors beyond connecting a wallet.
        </p>
      </Card>
    </div>
  );
};

export default Fund;
